// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrix_product
NumericMatrix matrix_product(Eigen::MatrixXd& tm, Eigen::MatrixXd& tm2);
RcppExport SEXP _scLineaR_matrix_product(SEXP tmSEXP, SEXP tm2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type tm(tmSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type tm2(tm2SEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_product(tm, tm2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scLineaR_matrix_product", (DL_FUNC) &_scLineaR_matrix_product, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scLineaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
